[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "london"
solc_version = "0.8.21"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
